name = "MapUnroll"
uuid = "cb3e49c6-be3c-4b9f-8a95-3e29188d9713"
authors = ["Alec Loudenback <alecloudenback@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
