name = "MapUnroll"
uuid = "cb3e49c6-be3c-4b9f-8a95-3e29188d9713"
authors = ["Alec Loudenback <alecloudenback@gmail.com> and contributors"]
version = "1.0.0"

[deps]
BangBang = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
MicroCollections = "128add7d-3638-4c79-886c-908ea0c25c34"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
BangBang = "0.4.4"
MicroCollections = "0.2.0"
Reexport = "1.2.2"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
